version: "2.0"

services:
  marketing_gateway_page:
    container_name: marketing_gateway_page
    image: quess-dashboard:0.0.1
    volumes:
      - ./app:/app
    ports:
      - 80:80

networks:
  defaults:
    driver: bridge
